### ISSUE TITLE
iOS Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by comoser** [AndrewBestbier/react-native-salesforce-chat#6]
Hello,

After adding the project to the dependencies and compiling the iOS project, I'm faced with the following error while building:

<img width="544" alt="captura de ecra 2018-09-18 as 12 31 28" src="https://user-images.githubusercontent.com/5495320/45684623-d0c8ff00-bb3e-11e8-83e7-468f9303ea75.png">

If there is any kind of help you can provide I would appreciate.

**Comment by AndrewBestbier** [comment]
Hi @comoser,

Apologies for the late response - I saw this by chance now. Did you manage to get anywhere with this?

**Comment by comoser** [comment]
Hey @AndrewBestbier 

After a bit of struggling I found out that I hadn't done the "Prepare for Deploy" phase of the documents.
After I did what was in the guide, everything compiled smoothly.
Thanks

**Comment by itjunkii83** [comment]
> "Prepare for Deploy"

Hey @comoser, what guide are you referencing with the instructions to overcome this error?

Thank you

**Comment by comoser** [comment]
- 

> > "Prepare for Deploy"
> 
> Hey @comoser, what guide are you referencing with the instructions to overcome this error?
> 
> Thank you


Hey There @itjunkii83 ! 

I'm sorry I didn't provide a link and only a name for the documentation section.

I was searching again for this and I think the page relevant to you is this one

https://developer.salesforce.com/docs/atlas.en-us.service_sdk_ios.meta/service_sdk_ios/prepare_for_appstore.htm#!

Good luck 😉
